kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: oidc-apps
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
      - containerPort: 30556
        hostPort: 5556
        protocol: TCP
