replicas: 1

global:
  oauth2Proxy:
    scope: "openid email profile"
    clientId: "grafana"
    clientSecret: "grafana-secret"
    oidcIssuerUrl: "https://dex.127.0.0.1.nip.io:5556"
    sslInsecureSkipVerify: true
    insecureOidcSkipIssuerVerification: true
  oidcCABundle: "OIDC_CA_BUNDLE_PLACEHOLDER"
  domainName: "127.0.0.1.nip.io"
  gateway:
    managed: true
    gatewayClassName: envoy
    httpRoutes:
      enabled: true
    listeners:
      - name: https
        protocol: HTTPS
        port: 443
        allowedRoutes:
          namespaces:
            from: All
        tls:
          mode: Terminate
          certificateRefs:
            - name: wildcard-tls

targets:
  - name: grafana
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: monitoring
    labelSelector:
      matchLabels:
        app: grafana
    targetPort: 3000
    targetProtocol: http
    httpRoute:
      create: true
