# SPDX-FileCopyrightText: 2026 nickytd
# SPDX-License-Identifier: Apache-2.0

FROM golang:1.26 AS builder

WORKDIR /src
COPY . .
RUN go mod download && cd tools && go mod download
RUN make build-watcher

FROM ghcr.io/kube-rbac-proxy/kube-rbac-proxy:v0.22.1 AS kube-rbac-proxy-watcher

COPY --from=builder /src/bin/watcher /usr/bin/watcher

ENTRYPOINT ["/usr/bin/watcher"]
