# SPDX-FileCopyrightText: 2026 nickytd
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.certificate.create -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "oidc-apps.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oidc-apps.certificateLabels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}