# SPDX-FileCopyrightText: 2026 nickytd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-apps.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oidc-apps.labels" . | nindent 4 }}
spec:
  replicas: {{ default 2 .Values.replicas }}
  selector:
    matchLabels:
      {{- include "oidc-apps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configuration: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.metrics.enableScraping }}
        prometheus.io/name: "{{ .Release.Name }}"
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        {{- end }}
      labels:
        {{- include "oidc-apps.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oidc-apps.serviceAccountName" . }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.priorityClass .Values.priorityClass.name }}
      priorityClassName: {{ .Values.priorityClass.name | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - "--log-format={{ .Values.logFormat }}"
          - "--log-level={{ .Values.logLevel }}"
          - "--config=/etc/controller.yaml"
          - "--use-cert-manager={{ .Values.certificate.create }}"
          - "--webhook-certs-dir=/etc/webhook"
          - "--webhook-name={{ include "oidc-apps.fullname" . }}"
          - "--webhook-port={{ .Values.service.port | int }}"
          {{- if .Values.imagePullSecrets }}
          {{- with (index .Values.imagePullSecrets 0) }}
          - "--registry-secret={{ .name }}"
          {{- end }}
          {{- end }}
          {{- if .Values.cacheSelectorStr }}
          - "--cache-selector={{ .Values.cacheSelectorStr }}"
          {{- end }}
          {{- if .Values.metrics.enableScraping }}
          - "--metrics-port={{ .Values.metrics.port | int }}"
          {{- end }}
          {{- if .Values.vpa.enabled }}
          - "--enable-vpa=true"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
          ports:
            - name: webhook
              containerPort: {{ .Values.service.port | int }}
              protocol: TCP
            {{- if .Values.metrics.enableScraping }}
            - name: metrics
              containerPort: {{ .Values.metrics.port | int }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/webhook
              name: certs
            - mountPath: /etc/controller.yaml
              name: configuration
              subPath: controller.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "oidc-apps.selectorLabels" . | nindent 14 }}
      volumes:
        - name: certs
        {{- if .Values.certificate.create }}
          projected:
            sources:
              - secret:
                  name: {{ include "oidc-apps.certificateSecretName" . }}
        {{- else }}
          emptyDir:
            medium: Memory
        {{- end }}
        - name: configuration
          secret:
            secretName: {{ include "oidc-apps.fullname" . }}
